import test from 'node:test';
import assert from 'node:assert/strict';
import {V,M,normalOf,transformedPoint,bounds,mergeBounds,rayBox,rayTriangle,BVH,finiteNumber} from '../src/core/math.js';
import {Solid,Polygon,box,cylinder,sphere,torus,tube,boolean,extrude,cleanProfile,rectangleProfile,revolve,loft,sweep,pullFace,shell,splitSolid,chamferBox,roundCorners,metrics,topology,featureEdges,repair,fillOpenings,sheetMetal,simplifyVertexClusters,sectionSegments,triangulate2D} from '../src/core/kernel.js';
import {Sketch,snapPoint} from '../src/core/sketch.js';
import {ModelDocument,body,MATERIALS} from '../src/core/document.js';
import {parseSTL,exportSTL,parseOBJ,exportOBJ,parsePLY,parseDXF,exportDXF,exportGLB,exportCSV} from '../src/core/io.js';
import {Camera} from '../src/render/camera.js';
import {drawingSVG} from '../src/ui/drawing.js';
import {actuatorExample} from '../src/core/examples.js';
const near=(a,b,eps=1e-7)=>assert.ok(Math.abs(a-b)<=eps*Math.max(1,Math.abs(b)),`${a} ≠ ${b} (relative tolerance ${eps})`);
const vecNear=(a,b,eps=1e-7)=>a.forEach((v,i)=>near(v,b[i],eps));
const volume=s=>metrics(s).volume;
const square=[[-5,-5],[5,-5],[5,5],[-5,5]];
const enc=t=>new TextEncoder().encode(t).buffer;
const closed=s=>assert.equal(topology(s).closed,true);

test('math: vector algebra and normal normalization',()=>{vecNear(V.cross([1,0,0],[0,1,0]),[0,0,1]);near(V.dot([1,2,3],[3,2,1]),10);vecNear(V.norm([0,0,0]),[0,0,0]);});
test('math: Newell normal tolerates initial collinear points',()=>vecNear(normalOf([[0,0,0],[1,0,0],[2,0,0],[2,2,0],[0,2,0]]),[0,0,1]));
test('math: inverse of combined affine transformation',()=>{let m=M.mul(M.translate([12,-4,90]),M.mul(M.rotate([1,2,3],.7),M.scale([2,3,-4])));vecNear(transformedPoint(M.inverse(m),transformedPoint(m,[7,8,9])),[7,8,9]);});
test('math: singular inverse and nonfinite dimensions reject',()=>{assert.throws(()=>M.inverse(M.scale([0,1,1])));assert.throws(()=>finiteNumber(NaN));assert.throws(()=>box(-1,1,1));});
test('math: empty and merged bounds are finite',()=>{vecNear(bounds([]).center,[0,0,0]);vecNear(mergeBounds([box(2,2,2).bounds,box(2,2,2,[5,0,0]).bounds]).size,[7,2,3]);});
test('math: ray box parallel and miss cases',()=>{const b=box(2,2,2,[0,0,0]).bounds;assert.ok(rayBox([0,0,4],[0,0,-1],b));assert.equal(rayBox([2,0,4],[0,0,-1],b),false);});
test('math: triangle ray barycentric hit / miss',()=>{let h=rayTriangle([.2,.2,4],[0,0,-1],[0,0,0],[1,0,0],[0,1,0]);near(h.t,4);near(h.u,.2);assert.equal(rayTriangle([2,2,4],[0,0,-1],[0,0,0],[1,0,0],[0,1,0]),null);});
test('math: BVH nearest hit and section filter',()=>{let s=box(10,10,10,[0,0,0]),b=s.bvh();near(b.hit([0,0,20],[0,0,-1]).t,15);near(b.hit([0,0,20],[0,0,-1],Infinity,p=>p[2]<0).t,25);});
test('camera: project and unproject intersect original XY point',()=>{let c=new Camera();c.matrices(1000,700);let p=[14,6,0],q=c.project(p);vecNear(c.planePoint(q[0],q[1],2,0),p);});
test('camera: orthographic and perspective projection stay finite',()=>{let c=new Camera();for(const mode of [false,true])for(const view of ['top','front','right','iso']){c.view(view);c.perspective=mode;c.matrices(500,700);assert.ok(c.project([0,0,0]).every(Number.isFinite));}});

test('kernel: box exact volume area centroid and closed winding',()=>{let s=box(10,20,30,[4,5,6]),m=metrics(s);near(m.volume,6000);near(m.area,2200);vecNear(m.centroid,[4,5,6]);closed(s);});
test('kernel: cylinder tessellation matches polygon-area formula',()=>{let s=cylinder(10,20,[0,0,0],64);near(volume(s),64/2*100*Math.sin(2*Math.PI/64)*20);closed(s);});
test('kernel: cone apex tessellation volume and closure',()=>{let s=cylinder(10,20,[0,0,10],64,0);near(volume(s),volume(cylinder(10,20,[0,0,10],64))/3);closed(s);});
test('kernel: sphere volume converges toward analytic value',()=>{let a=sphere(10,[0,0,0],16,8),b=sphere(10,[0,0,0],64,32),exact=4*Math.PI*1000/3;assert.ok(Math.abs(volume(b)-exact)<Math.abs(volume(a)-exact));near(volume(b),exact,.01);closed(b);});
test('kernel: torus closed and near analytic volume',()=>{let s=torus(20,4,[0,0,4],64,32);near(volume(s),2*Math.PI**2*20*16,.01);closed(s);});
test('kernel: tube has an open bore with closed material boundary',()=>{let s=tube(10,5,20,[0,0,10],64);near(volume(s),64/2*(100-25)*Math.sin(2*Math.PI/64)*20);closed(s);assert.equal(s.bvh().hit([0,0,40],[0,0,-1]),null);});
test('kernel: rotated and reflected solids retain positive signed volume',()=>{let s=box(10,20,30).transform(M.mul(M.rotate([1,1,0],.45),M.scale([-2,3,4])));near(metrics(s).signedVolume,6000*24);closed(s);});
test('kernel: translation preserves primitive parameters and updates center',()=>{let s=box(10,20,30,[0,0,15]).translate([5,6,7]);assert.equal(s.meta.type,'box');vecNear(s.meta.center,[5,6,22]);});
test('kernel: nontranslation transforms deliberately discard primitive metadata',()=>assert.deepEqual(box().transform(M.rotate([1,0,0],.2)).meta,{}));
test('kernel: immutable derived caches reuse metrics bounds and BVH',()=>{let s=box();assert.equal(s.bounds,s.bounds);assert.equal(metrics(s),metrics(s));assert.equal(s.bvh(),s.bvh());});
test('kernel: solid JSON roundtrip and invalid vertices',()=>{let a=box(),b=Solid.fromJSON(JSON.parse(JSON.stringify(a)));near(volume(a),volume(b));assert.throws(()=>Solid.fromJSON({polygons:[{v:[[NaN,0,0],[0,1,0],[1,0,0]]}]}));});
test('kernel: concave profile extrusion preserves area and cap triangulation',()=>{let s=extrude([[0,0],[20,0],[20,10],[10,10],[10,20],[0,20]],5);near(volume(s),1500);closed(s);});
test('kernel: extrusion normalizes clockwise contours',()=>{let s=extrude(square.slice().reverse(),5);near(volume(s),500);assert.ok(metrics(s).signedVolume>0);closed(s);});
test('kernel: invalid zero-area and crossing profiles reject',()=>{assert.throws(()=>extrude([[0,0],[1,0],[2,0]],10));assert.throws(()=>extrude([[0,0],[10,10],[0,10],[10,0]],10));});
test('kernel: rounded rectangle has correct bounds and reduced volume',()=>{let s=box(40,30,10,[0,0,5],4);vecNear(s.bounds.size,[40,30,10]);assert.ok(volume(s)<12000);closed(s);});

for(const [op,expected] of [['union',1500],['subtract',500],['intersect',500]])test(`CSG: overlapping boxes ${op} exact volume`,()=>{let s=boolean(box(10,10,10,[0,0,0]),box(10,10,10,[5,0,0]),op);near(volume(s),expected);assert.ok(s.polygons.length);});
test('CSG: disjoint set identities',()=>{let a=box(10,10,10),b=a.translate([100,0,0]);near(volume(boolean(a,b,'union')),2000);near(volume(boolean(a,b,'subtract')),1000);assert.equal(boolean(a,b,'intersect').polygons.length,0);});
test('CSG: empty set identities and unknown operation rejection',()=>{let a=box(10,10,10),e=new Solid();near(volume(boolean(e,a)),1000);assert.equal(boolean(e,a,'subtract').polygons.length,0);assert.throws(()=>boolean(a,a,'xor'));});
test('CSG: subtract through-hole and ray query',()=>{let s=boolean(box(30,30,10,[0,0,5]),cylinder(5,20,[0,0,5],32),'subtract');near(volume(s),9000-volume(cylinder(5,10,[0,0,5],32)));assert.equal(s.bvh().hit([0,0,30],[0,0,-1]),null);});
test('CSG: operands remain unmodified',()=>{let a=box(),b=cylinder();let before=JSON.stringify([a,b]);boolean(a,b,'subtract');assert.equal(JSON.stringify([a,b]),before);});
test('CSG: overlapping face IDs are namespaced across operands',()=>{let a=box(20,20,20),b=Solid.fromJSON(a.toJSON()).translate([5,5,5]),s=boolean(a,b,'subtract'),groups=new Map();for(const p of s.polygons){if(groups.has(p.id)){let q=groups.get(p.id);near(Math.abs(V.dot(p.normal,q.normal)),1);near(Math.abs(p.w),Math.abs(q.w));}else groups.set(p.id,p);}});
test('CSG: concave polygon operands are triangulated before BSP',()=>{let p=extrude([[0,0],[20,0],[20,10],[10,10],[10,20],[0,20]],10),s=boolean(p,box(5,5,20,[3,3,5]),'subtract');near(volume(s),2750);});

test('direct edit: pulling shared top-face vertices changes box height',()=>{let a=box(10,20,30,[0,0,15]),f=a.polygons.find(p=>p.normal[2]>.9),s=pullFace(a,f.id,5);near(volume(s),7000);near(s.bounds.max[2],35);closed(s);});
test('direct edit: inward pull and collapse rejection',()=>{let a=box(10,10,10),f=a.polygons.find(p=>p.normal[2]>.9);near(volume(pullFace(a,f.id,-4)),600);assert.throws(()=>pullFace(a,f.id,-10));assert.throws(()=>pullFace(a,'missing',2));});
test('direct edit: pulling noncoplanar face groups rejects',()=>{let a=box();a.polygons[1].id=a.polygons[4].id;assert.throws(()=>pullFace(a,a.polygons[1].id,1));});
test('direct edit: primitive open-top box shell volume',()=>{let s=shell(box(20,20,20,[0,0,10]),2);near(volume(s),8000-16*16*18);assert.ok(s.bvh().hit([0,0,40],[0,0,-1]).point[2]<2.001);});
test('direct edit: primitive cylinder shell removes correct inner volume',()=>{let s=shell(cylinder(10,20,[0,0,10],32),2);near(volume(s),volume(cylinder(10,20,[0,0,10],32))-volume(cylinder(8,18,[0,0,11],32)));});
test('direct edit: shell rejects unsupported shapes and excessive thickness',()=>{assert.throws(()=>shell(sphere(),1));assert.throws(()=>shell(box(10,10,10),6));});
test('direct edit: plane split conserves volume',()=>{let parts=splitSolid(box(10,20,30,[0,0,15]),2,12);near(volume(parts[0]),2400);near(parts.reduce((s,p)=>s+volume(p),0),6000);});
test('direct edit: all-edge box chamfer is closed and removes material',()=>{let s=chamferBox(box(20,20,20,[0,0,10]),2);assert.ok(volume(s)<8000&&volume(s)>7000);closed(s);});
test('direct edit: rounded vertical corners retain height',()=>{let a=box(20,20,30),b=roundCorners(a,4);near(b.bounds.size[2],30);assert.ok(volume(b)<volume(a));assert.throws(()=>roundCorners(sphere(),2));});
test('form: full radial revolve matches annular cylinder',()=>{let r=revolve([[5,0],[10,0],[10,20],[5,20]],360,64);near(volume(r),volume(tube(10,5,20,[0,0,10],64)));closed(r);});
test('form: partial revolve has capped ends',()=>{let r=revolve([[5,0],[10,0],[10,20],[5,20]],180,64);near(volume(r),volume(tube(10,5,20,[0,0,10],64))/2);closed(r);});
test('form: loft of identical profiles equals an extrusion',()=>{let s=loft(square,square,20);near(volume(s),2000);closed(s);});
test('form: ruled twisted loft has valid winding and closed edges',()=>{let s=loft(rectangleProfile(30,30),rectangleProfile(15,15),30,[5,0],25);assert.ok(metrics(s).signedVolume>0);closed(s);assert.throws(()=>loft(square,[[0,0],[5,0],[5,5]],20));});
test('form: straight profile sweep equals an extrusion',()=>{let s=sweep(square,[[0,0,0],[0,0,20]]);near(volume(s),2000);closed(s);});
test('form: bent sweep closes material boundary',()=>closed(sweep(rectangleProfile(3,3),[[0,0,0],[0,0,20],[10,0,30],[30,0,30]])));
test('form: invalid sweep and negative revolve radii reject',()=>{assert.throws(()=>sweep(square,[[0,0,0],[0,0,0]]));assert.throws(()=>revolve([[-2,0],[10,0],[10,10]],360));});

test('repair: detects and fills one planar opening',()=>{let a=box(10,10,10),open=new Solid(a.polygons.filter(p=>p.normal[2]<.9));assert.ok(topology(open).boundary.length);let f=fillOpenings(open);assert.equal(f.count,1);closed(f.solid);near(volume(f.solid),1000);});
test('repair: removes duplicate faces without changing volume',()=>{let a=box(),b=new Solid([...a.polygons,a.polygons[0].clone()]),r=repair(b);assert.equal(r.removed,1);near(volume(r.solid),volume(a));closed(r.solid);});
test('repair: conforming T junction repair closes Boolean incidence',()=>{let a=boolean(box(30,30,10),cylinder(4,30), 'subtract'),r=repair(a);closed(r.solid);near(volume(r.solid),volume(a));});
test('repair: diagnostics detect inconsistent winding',()=>{let a=box();let b=new Solid(a.polygons.map((p,i)=>i===2?p.clone().flip():p.clone()));assert.ok(topology(b).inconsistent.length);assert.equal(topology(b).closed,false);});
test('display: box has exactly twelve feature edges',()=>assert.equal(featureEdges(box()).length,12));
test('display: Boolean feature edges normalize internal T junctions',()=>{let a=boolean(box(30,30,10),cylinder(4,30), 'subtract');let edges=featureEdges(a);assert.ok(edges.length>12);assert.equal(featureEdges(a),edges);});
test('section: plane intersects box on four geometric sides',()=>{let segs=sectionSegments(box(10,10,10),2,5);assert.ok(segs.length>=4);for(let s of segs)for(let p of s)near(p[2],5);});
test('mesh: clustering reduction reduces a dense sphere',()=>{let a=sphere(10,[0,0,10],48,24),b=simplifyVertexClusters(a,2);assert.ok(b.triangles().length<a.triangles().length);assert.ok(b.triangles().length>0);});
test('sheet: developed length follows explicit K-factor formula',()=>{let s=sheetMetal({width:40,base:30,flange:20,thickness:2,radius:4,angle:90,kfactor:.42,flat:true});let allowance=Math.PI/2*(4+.42*2);near(s.meta.allowance,allowance);near(s.bounds.size[0],50+allowance);near(volume(s),40*2*(50+allowance));closed(s);});
test('sheet: bend cross-section is closed and refoldable',()=>{let a=sheetMetal(),b=sheetMetal({...a.meta,flat:true}),c=sheetMetal({...b.meta,flat:false});closed(a);near(volume(a),volume(c));assert.ok(b.bounds.size[2]<a.bounds.size[2]);});

test('sketch: horizontal and length constraints converge',()=>{let s=new Sketch([[0,0],[8,3]]);s.add('fixed',0,0,[0,0]).add('horizontal',0,1).add('distance',0,1,10);let r=s.solve();assert.ok(r.converged);vecNear(s.points[1],[10,0],1e-5);});
test('sketch: vertical and coincident constraints converge',()=>{let s=new Sketch([[0,0],[2,8],[3,9]]);s.add('fixed',0,0,[0,0]).add('vertical',0,1).add('distance',0,1,10).add('coincident',1,2);assert.ok(s.solve().converged);vecNear(s.points[1],[0,10],1e-5);vecNear(s.points[2],[0,10],1e-5);});
test('sketch: perpendicular and equal edges',()=>{let s=new Sketch([[0,0],[8,1],[9,8]],false);s.add('fixed',0,0,[0,0]).add('horizontal',0,1).add('distance',0,1,10).add('perpendicular',0,1).add('equal',0,1);assert.ok(s.solve().converged);near(V.dist(s.points[1],s.points[2]),10,1e-5);});
test('sketch: conflicting constraints leave source unchanged',()=>{let s=new Sketch([[0,0],[8,0]]),before=structuredClone(s.points);s.add('distance',0,1,10).add('distance',0,1,20);assert.equal(s.solve().converged,false);assert.deepEqual(s.points,before);});
test('sketch: invalid point references reject',()=>{let s=new Sketch([[0,0],[1,1]]);s.add('distance',0,4,10);assert.throws(()=>s.solve());});
test('sketch: vertex snap precedes grid snap',()=>{assert.deepEqual(snapPoint([4.9,5.1],5,[[5.2,5.2]],1),{point:[5.2,5.2],type:'vertex'});vecNear(snapPoint([8,11],5).point,[10,10]);});
test('sketch: world placement on all principal planes',()=>{vecNear(new Sketch([],true,'XY',7).worldPoint([2,3]),[2,3,7]);vecNear(new Sketch([],true,'XZ',7).worldPoint([2,3]),[2,7,3]);vecNear(new Sketch([],true,'YZ',7).worldPoint([2,3]),[7,2,3]);});

test('document: transactions support undo and redo of real geometry',()=>{let d=new ModelDocument();d.transact('create',()=>d.add(box(),'A'));assert.equal(d.bodies.length,1);assert.ok(d.undo());assert.equal(d.bodies.length,0);assert.ok(d.redo());assert.equal(d.bodies[0].name,'A');});
test('document: transaction rollback is atomic on validation error',()=>{let d=new ModelDocument();assert.throws(()=>d.transact('bad',()=>{let b=d.add(box(),'A');b.color='invalid';}));assert.equal(d.bodies.length,0);assert.equal(d.history.length,0);});
test('document: new edit truncates redo branch',()=>{let d=new ModelDocument();d.transact('A',()=>d.add(box(),'A'));d.transact('B',()=>d.add(box(),'B'));d.undo();d.transact('C',()=>d.add(box(),'C'));assert.equal(d.redo(),false);assert.deepEqual(d.bodies.map(b=>b.name),['A','C']);});
test('document: structural history shares immutable solids',()=>{let d=new ModelDocument(),s=box();d.transact('A',()=>d.add(s));d.transact('name',()=>d.bodies[0].name='B');assert.equal(d.history[1].before.bodies[0].solid,s);});
test('document: hidden layers affect visibility and bounds',()=>{let d=new ModelDocument();d.add(box());assert.equal(d.visible().length,1);d.layers[0].visible=false;assert.equal(d.visible().length,0);vecNear(d.bounds().size,[0,0,0]);});
test('document: native roundtrip retains materials groups and units',()=>{let d=new ModelDocument();d.name='Unit test';d.units='in';let b=d.add(box(),'A','brass');d.groups=[{id:'g',name:'Fixture',ids:[b.id]}];let n=ModelDocument.parse(JSON.stringify(d.serialize()));assert.equal(n.name,d.name);assert.equal(n.units,'in');assert.equal(n.bodies[0].material,'brass');assert.equal(n.groups[0].ids[0],b.id);near(volume(n.bodies[0].solid),volume(b.solid));});
test('document: duplicate IDs and invalid format reject',()=>{let d=new ModelDocument();d.add(box());let x=d.serialize();x.bodies.push(x.bodies[0]);assert.throws(()=>ModelDocument.parse(x));assert.throws(()=>ModelDocument.parse('{}'));});
test('document: mass report uses explicit material density',()=>{let d=new ModelDocument();d.add(box(10,10,10),'A','steel');near(d.report().totalMass_g,7.85);});

test('I/O: binary STL roundtrip preserves volume and triangle count',()=>{let a=body(box(10,20,30)),data=exportSTL([a]),s=parseSTL(data);assert.equal(new DataView(data).getUint32(80,true),12);near(volume(s),6000);closed(s);});
test('I/O: ASCII STL parses real triangle coordinates',()=>{let s=parseSTL(enc('solid a\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 0 1 0\nendloop\nendfacet\nendsolid'));near(metrics(s).area,.5);});
test('I/O: truncated and nonfinite STL reject',()=>{assert.throws(()=>parseSTL(exportSTL([body(box())]).slice(0,100)));assert.throws(()=>parseSTL(enc('not STL')));let a=exportSTL([body(box())]);new DataView(a).setFloat32(96,Infinity,true);assert.throws(()=>parseSTL(a));});
test('I/O: OBJ export and negative face indices roundtrip',()=>{let a=box(10,20,30),b=parseOBJ(exportOBJ([body(a)])).solid;near(volume(a),volume(b));let q=parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf -3 -2 -1');near(metrics(q.solid).area,.5);});
test('I/O: invalid OBJ face indices reject',()=>{assert.throws(()=>parseOBJ('v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 8'));assert.throws(()=>parseOBJ('v 0 0 0\nf 0 1 1'));});
test('I/O: ASCII PLY respects declared property order',()=>{let s=parsePLY('ply\nformat ascii 1.0\nelement vertex 3\nproperty float z\nproperty float x\nproperty float y\nelement face 1\nproperty list uchar int vertex_indices\nend_header\n0 0 0\n0 1 0\n0 0 1\n3 0 1 2\n');near(metrics(s).area,.5);});
test('I/O: binary PLY explicitly rejects',()=>assert.throws(()=>parsePLY('ply\nformat binary_little_endian 1.0\nend_header')));
test('I/O: GLB has valid aligned chunks and millimeter-to-meter Y-up conversion',()=>{let data=exportGLB([body(box(1000,2000,3000,[0,0,1500]))]),v=new DataView(data),n=v.getUint32(12,true),j=JSON.parse(new TextDecoder().decode(new Uint8Array(data,20,n)));assert.equal(v.getUint32(0,true),0x46546c67);assert.equal(v.getUint32(4,true),2);assert.equal(v.getUint32(8,true),data.byteLength);assert.equal(n%4,0);vecNear(j.accessors[0].min,[-.5,0,-1]);vecNear(j.accessors[0].max,[.5,3,1]);assert.equal(j.meshes.length,1);});
test('I/O: DXF preserves world coordinates for XZ sketches',()=>{let d=exportDXF([],[{points:[[2,3],[4,5]],closed:false,plane:'XZ',origin:7}]);assert.ok(d.includes('10\n2\n20\n7\n30\n3\n11\n4\n21\n7\n31\n5'));});
test('I/O: DXF imports straight polylines and circles',()=>{let p=parseDXF('0\nSECTION\n2\nENTITIES\n0\nLWPOLYLINE\n70\n1\n10\n0\n20\n0\n10\n10\n20\n0\n10\n10\n20\n10\n0\nCIRCLE\n10\n2\n20\n3\n40\n5\n0\nEOF\n');assert.equal(p.length,2);assert.equal(p[0].closed,true);assert.equal(p[1].points.length,64);});
test('I/O: DXF bulge arcs reject instead of silently flattening',()=>assert.throws(()=>parseDXF('0\nLWPOLYLINE\n10\n0\n20\n0\n42\n1\n10\n1\n20\n1\n0\nEOF\n')));
test('I/O: CSV escapes quotes and guards spreadsheet-formula names',()=>{let s=exportCSV({bodies:[{name:'=1+2',material:'a"b',volume_mm3:1,area_mm2:2,mass_g:3,triangles:4}]});assert.ok(s.includes('"\'=1+2"'));assert.ok(s.includes('"a""b"'));});
test('drawing: SVG contains three real projections and escaped title',()=>{let d=drawingSVG([body(box())],'<test&design>');assert.ok(d.includes('<svg'));assert.ok(d.includes('&lt;test&amp;design&gt;'));assert.ok(d.includes('TOP'));assert.ok(d.includes('FRONT'));assert.ok(d.includes('RIGHT'));assert.ok(!d.includes('<test&design>'));});
test('example: 19-body assembly is real geometry with open mounting holes',()=>{let e=actuatorExample();assert.equal(e.bodies.length,19);assert.equal(e.components.length,4);assert.ok(e.bodies.reduce((n,b)=>n+b.solid.triangles().length,0)>10000);assert.equal(e.bodies[0].solid.bvh().hit([-49,-31,20],[0,0,-1]),null);});

test('camera: empty-document fit retains useful sketch scale',()=>{let c=new Camera();c.fit(bounds([]));assert.ok(c.span>=100);});
test('document: imported prototype property names cannot masquerade as materials',()=>{let d=new ModelDocument();d.add(box(),'Safe material');let json=d.serialize();json.bodies[0].material='__proto__';let parsed=ModelDocument.parse(json);assert.equal(parsed.bodies[0].material,'aluminum');near(parsed.report().bodies[0].mass_g,40*30*25*.0027);assert.equal(body(box(),'B','constructor').material,'aluminum');});
test('I/O: truncated ASCII PLY is rejected rather than imported partially',()=>assert.throws(()=>parsePLY('ply\nformat ascii 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nelement face 2\nproperty list uchar int vertex_indices\nend_header\n0 0 0\n1 0 0\n0 1 0\n3 0 1 2\n'),/Truncated/));
