import test from 'node:test';import assert from 'node:assert/strict';
import {box} from '../src/core/kernel.js';import {ModelDocument} from '../src/core/document.js';
import {assemblyReference,solveAssembly,applyAssemblySolution} from '../src/engineering/assembly.js';
import {motionStudy} from '../src/engineering/motion.js';import{panelLayout,panelBendCSV}from'../src/engineering/sheet-panel.js';
function setup(type='drivenRevolute',value=60){const d=new ModelDocument();d.bodies=[];const a=d.add(box(10,10,10),'Fixed'),b=d.add(box(5,5,5),'Moving');const m={id:'drive',type,value,a:assemblyReference(a,[0,0,0],[0,0,1],[1,0,0]),b:assemblyReference(b,[0,0,0],[0,0,1],[1,0,0])};return{d,a,b,m};}
test('Driven revolute removes the remaining twist DOF',()=>{const{d,a,m}=setup();const r=solveAssembly(d.bodies,[m],[a.id]);assert.ok(r.converged);assert.equal(r.degreesOfFreedom,0);assert.equal(r.mateResiduals.length,1);});
test('Driven slider places its local datum at commanded travel',()=>{const{d,a,b,m}=setup('drivenSlider',25);const r=solveAssembly(d.bodies,[m],[a.id]);assert.ok(r.converged);applyAssemblySolution(d,r);assert.ok(Math.abs(b.solid.bounds.center[2]+22.5)<1e-4);assert.equal(r.degreesOfFreedom,0);});
test('A target outside drive limits is rejected',()=>{const{d,a,m}=setup();m.limits=[-20,20];assert.throws(()=>solveAssembly(d.bodies,[m],[a.id]),/outside/);});
test('Un-driven revolute preserves one free coordinate and reports limits',()=>{const{d,a,m}=setup('revolute');m.limits=[-30,30];const r=solveAssembly(d.bodies,[m],[a.id]);assert.ok(r.converged);assert.equal(r.degreesOfFreedom,1);});
test('Screw relation couples axial translation to twist',()=>{const{d,a,b,m}=setup('screw');m.pitch=5;const drive={...structuredClone(m),id:'angle',type:'angle',value:0};const r=solveAssembly(d.bodies,[m,drive],[a.id]);assert.ok(r.converged);assert.equal(r.degreesOfFreedom,1);assert.throws(()=>solveAssembly(d.bodies,[{...m,pitch:0}],[a.id]));});
test('Motion continuation exports solved absolute transforms without source mutation',()=>{const{d,a,b,m}=setup();const before=JSON.stringify(d.serialize()),r=motionStudy(d.bodies,[m],[a.id],{mateId:'drive',from:-60,to:60,frames:9});assert.equal(r.frames.length,9);assert.equal(JSON.stringify(d.serialize()),before);assert.ok(r.frames.every(f=>f.maxResidual<1e-5));assert.notDeepEqual(r.frames[0].transforms[b.id],r.frames.at(-1).transforms[b.id]);});
test('Failed motion frame does not leave a partly edited source',()=>{const{d,a,m}=setup();m.limits=[-20,20];const before=JSON.stringify(d.serialize());assert.throws(()=>motionStudy(d.bodies,[m],[a.id],{mateId:'drive',from:0,to:30}));assert.equal(JSON.stringify(d.serialize()),before);});
test('Panel CSV records explicit production inputs without asserting certification',()=>{const d={flanges:[{edge:0,allowance:8}],grainAngle:45};assert.equal(panelLayout(d).bends[0].allowance,8);assert.match(panelBendCSV(d),/measured allowance/);assert.match(panelBendCSV(d),/45/);});
