import test from'node:test';import assert from'node:assert/strict';import{initialize3dm,disposeNative}from'../src/engineering/native-3dm.js';import{initializeExact}from'../src/engineering/exact-engine.js';import{M}from'../src/core/math.js';
const n=await initialize3dm(),r=n.r,e=await initializeExact();
const surface={poles:[[[0,0,0],[0,10,0]],[[10,0,0],[10,10,5]]],weights:[[1,1],[1,1]],uDegree:1,vDegree:1,uKnots:[0,1],vKnots:[0,1],uMultiplicities:[2,2],vMultiplicities:[2,2]};
function file(geometry,unit=r.UnitSystem.Millimeters){const f=new r.File3dm(),s=f.settings(),t=f.objects(),a=new r.ObjectAttributes();try{s.modelUnitSystem=unit;a.name='Native fixture';t.add(geometry,a);return f.toByteArray();}finally{a.delete();disposeNative(t);s.delete();f.delete();}}
test('Native .3dm weighted surface round-trips as editable OCCT NURBS',async()=>{const d=structuredClone(surface);d.weights[1][1]=2;const out=await n.run('export3dm',{objects:[{name:'Weighted',surface:d}]}),input=await n.run('import3dm',{bytes:out.bytes});assert.equal(input.objects[0].kind,'surface');assert.deepEqual(input.objects[0].surface.weights,d.weights);assert.deepEqual(input.objects[0].surface.poles,d.poles);const p=await e.run('nurbs',input.objects[0].surface);assert.ok(p.properties.valid);assert.equal(p.faces[0].type,'BSPLINE_SURFACE');});
test('Trimmed .3dm box reconstructs as a valid closed analytic B-rep',async()=>{const bbox=new r.BoundingBox([0,0,0],[20,30,40]),b=r.Brep.createFromBoundingBox(bbox);try{const input=await n.run('import3dm',{bytes:file(b)}),p=await e.run('from3dmBrep',{brep:input.objects[0].brep});assert.equal(p.properties.valid,true);assert.equal(p.properties.solidCount,1);assert.ok(Math.abs(p.properties.volume-24000)<1e-5);}finally{b.delete();bbox.delete();}});
test('Retained native geometry re-exports with exact rigid placement',async()=>{const out=await n.run('export3dm',{objects:[{name:'Before',surface}]}),input=await n.run('import3dm',{bytes:out.bytes}),m=M.translate([10,20,30]),second=await n.run('export3dm',{objects:[{name:'After',native3dm:input.objects[0].native3dm,pose:m}]}),third=await n.run('import3dm',{bytes:second.bytes});assert.deepEqual(third.objects[0].surface.poles[0][0],[10,20,30]);assert.match(second.report[0].representation,/retained/);});
test('3dm meshes remain explicitly faceted rather than mislabeled as exact solids',async()=>{const mesh={positions:[0,0,0,10,0,0,0,10,0],indices:[0,1,2]},out=await n.run('export3dm',{objects:[{mesh}]}),input=await n.run('import3dm',{bytes:out.bytes});assert.equal(input.objects[0].kind,'mesh');assert.deepEqual(input.objects[0].mesh,mesh);assert.match(out.report[0].representation,/not analytic/);});
test('Unit conversion of native .3dm surfaces preserves millimetre dimensions',async()=>{const out=await n.run('export3dm',{objects:[{surface}]}),f=r.File3dm.fromByteArray(out.bytes),s=f.settings();s.modelUnitSystem=r.UnitSystem.Inches;const input=await n.run('import3dm',{bytes:f.toByteArray()});assert.equal(input.unitsScale,25.4);assert.ok(Math.abs(input.objects[0].surface.poles[1][0][0]-254)<1e-9);s.delete();f.delete();});
test('Unsupported objects cause strict import to fail without losing supported bodies',async()=>{const out=await n.run('export3dm',{objects:[{surface}]}),f=r.File3dm.fromByteArray(out.bytes),t=f.objects(),a=new r.ObjectAttributes();t.addPoint([0,0,0],a);const bytes=f.toByteArray();await assert.rejects(n.run('import3dm',{bytes}),/refused to lose/);const result=await n.run('import3dm',{bytes,allowPartial:true});assert.equal(result.objects.length,1);assert.equal(result.unsupported.length,1);a.delete();disposeNative(t);f.delete();});
test('Unsupported singular/seamed B-reps are rejected instead of imported untrimmed',async()=>{const sphere=new r.Sphere([0,0,0],10),b=r.Brep.createFromSphere(sphere);try{await assert.rejects(n.run('import3dm',{bytes:file(b)}),/Singular/);}finally{b.delete();sphere.delete();}});
test('Corrupt inputs and non-finite mesh exports are rejected',async()=>{await assert.rejects(n.run('import3dm',{bytes:new Uint8Array([1,2,3])}));await assert.rejects(n.run('export3dm',{objects:[{mesh:{positions:[NaN,0,0],indices:[0,0,0]}}]}));});
