import {featureEdges} from '../core/kernel.js';
import {mergeBounds} from '../core/math.js';
import {esc} from './icons.js';
export function drawingSVG(bodies,name='Design',units='mm'){
  const b=mergeBounds(bodies.map(x=>x.solid.bounds)),edges=bodies.flatMap(x=>featureEdges(x.solid)),factor=units==='in'?1/25.4:1;
  const fmt=v=>(v*factor).toFixed(units==='in'?3:1),sc=Math.min(132/Math.max(b.size[0],b.size[1],1),69/Math.max(b.size[1],b.size[2],1),1),views=[{label:'TOP',axes:[0,1],cx:111,cy:89},{label:'FRONT',axes:[0,2],cx:111,cy:199},{label:'RIGHT',axes:[1,2],cx:293,cy:199}];
  const project=(p,v)=>[v.cx+(p[v.axes[0]]-b.center[v.axes[0]])*sc,v.cy-(p[v.axes[1]]-b.center[v.axes[1]])*sc];
  let paths=views.map(v=>{
    let path=edges.map(([a,b])=>{let p=project(a,v),q=project(b,v);return `M${p[0].toFixed(3)},${p[1].toFixed(3)}L${q[0].toFixed(3)},${q[1].toFixed(3)}`;}).join(' '),w=b.size[v.axes[0]]*sc,h=b.size[v.axes[1]]*sc,x=v.cx-w/2,y=v.cy+h/2+10;
    return `<g><path d="${path}" fill="none" stroke="#344151" stroke-width=".2" stroke-linejoin="round"/><text x="${v.cx}" y="${v.cy-h/2-10}" class="view-label" text-anchor="middle">${v.label}</text><path d="M${x},${y-7}V${y+3}M${x+w},${y-7}V${y+3}" class="dimension"/><path d="M${x},${y}H${x+w}" class="dimension" marker-start="url(#arrow)" marker-end="url(#arrow)"/><rect x="${v.cx-13}" y="${y-2.7}" width="26" height="5" fill="white"/><text x="${v.cx}" y="${y+1}" text-anchor="middle" class="dimtext">${fmt(b.size[v.axes[0]])}</text></g>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="420mm" height="297mm" viewBox="0 0 420 297" role="img" aria-label="${esc(name)} engineering drawing"><defs><marker id="arrow" markerWidth="6" markerHeight="4" refX="3" refY="2" orient="auto-start-reverse"><path d="M6,0L0,2L6,4" fill="none" stroke="#82909d" stroke-width=".6"/></marker></defs><style>text{font-family:Arial,sans-serif;fill:#263440;font-size:3.2px}.view-label{font-size:3px;letter-spacing:.5px;fill:#71808c}.dimension{fill:none;stroke:#82909d;stroke-width:.18}.dimtext{font-size:3px}</style><rect width="420" height="297" fill="white"/><rect x="9" y="9" width="402" height="279" fill="none" stroke="#465460" stroke-width=".3"/><path d="M9 19H411M9 261H411" fill="none" stroke="#465460" stroke-width=".2"/><text x="15" y="15.5" style="font-size:3.5px;font-weight:bold;letter-spacing:1px">AVOLITH / ENGINEERING</text><text x="405" y="15.5" text-anchor="end" style="fill:#71808c">ORTHOGRAPHIC WIRE PROJECTIONS</text>${paths}<text x="219" y="54" style="font-size:3px;fill:#71808c">MODEL INFORMATION</text><text x="219" y="65" style="font-size:5px">${esc(name)}</text><text x="219" y="77">${bodies.length} bodies · faceted geometry</text><text x="219" y="85">Envelope: ${fmt(b.size[0])} × ${fmt(b.size[1])} × ${fmt(b.size[2])} ${units}</text><text x="219" y="99" style="fill:#71808c;font-size:2.8px">All feature edges are shown. Hidden lines are not removed.</text><text x="15" y="270">DIMENSIONS IN ${units.toUpperCase()} · DO NOT SCALE DRAWING</text><text x="15" y="278" style="fill:#71808c;font-size:2.8px">Generated from the current faceted model. Verify dimensions before manufacture.</text><path d="M210 261V288M365 261V288M210 276H411" stroke="#465460" stroke-width=".2"/><text x="214" y="267" style="font-size:2.5px;fill:#71808c">TITLE</text><text x="214" y="273" style="font-size:4px">${esc(name.slice(0,44))}</text><text x="214" y="284">SCALE ${sc.toFixed(3)}:1</text><text x="295" y="284">SHEET 1 / 1</text><text x="370" y="267" style="font-size:2.5px;fill:#71808c">FORMAT</text><text x="370" y="273">A3</text><text x="370" y="284">REV 01</text></svg>`;
}
