/** Advanced workbench. Native edits, numerical reports and drawing exports share undo and cancellation. */
import {exactInput,solidFromExact,exactFaceIndex} from './exact-client.js';
import {sectionSVG,sectionDXF} from './sections.js';
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
const jsonInput=(name,label,value)=>`<label class="field engineering-json"><span>${esc(label)}</span><textarea id="f-${name}" name="${name}" rows="8" spellcheck="false">${esc(JSON.stringify(value,null,2))}</textarea></label>`;
const parse=(data,name)=>{const s=data.get(name);if(typeof s!=='string'||s.length>250000)throw Error('JSON input exceeds 250 KB.');try{return JSON.parse(s);}catch{throw Error(`Invalid JSON: ${name}.`);}};
const ids=s=>{const a=String(s).trim()?String(s).split(/[ ,;]+/).map(Number):[];if(a.some(x=>!Number.isInteger(x)||x<0))throw Error('Topology indices must be non-negative integers.');return [...new Set(a)];};
const vector=s=>{const v=String(s).split(/[ ,;]+/).map(Number);if(v.length!==3||!v.every(Number.isFinite))throw Error('Enter x, y, z coordinates.');return v;};
await new Promise(resolve=>{const poll=()=>window.avolith?.engineering?resolve():setTimeout(poll,25);poll();});
const app=window.avolith,eng=app.engineering,{field,modal,val,download,toast}=app.ui;
const note=s=>`<div class="note">${s}</div>`;
const one=()=>{const bs=app.ui.selectedBodies();if(bs.length!==1)throw Error('Select one exact body.');if(bs[0].locked)throw Error('Unlock the selected body first.');exactInput(bs[0]);return bs[0];};
const index=(b,kind='faces')=>field(kind,kind==='faces'?'Face index (zero-based)':'Edge indices; blank selects all',kind==='faces'?String(exactFaceIndex(app.state,b)??0):'',{type:'text',optional:kind==='edges'});
const report=(title,obj)=>modal(title,`<pre class="engineering-report">${esc(JSON.stringify(obj,null,2))}</pre>`,null,'Close',true);
let lastSection=null,lastSectionSVG='';
function showSection(section,options){lastSection=section;lastSectionSVG=sectionSVG(section,options);const panel=document.getElementById('drawings');panel.innerHTML=`<div class="drawing-bar"><strong>${esc(options.name||'Section A–A')}</strong><button data-cmd="model">Back to model</button><button data-cmd="advanced-section-export">Export section</button></div><div class="engineering-sheet">${lastSectionSVG}</div>`;panel.hidden=false;app.state.drawing=true;app.state.exactDrawing=true;app.renderer.request();}
const actions={
 'advanced-fillet':()=>{const b=one();modal('Variable-radius edge fillet',index(b,'edges')+jsonInput('stations','Normalized edge fraction and radius (mm)',[[0,1],[.5,3],[1,2]])+note('The kernel interpolates radius stations along each selected contour. Infeasible blends are rejected without changing the source.'),async data=>eng.modify(b,'filletLaw',{edges:ids(data.get('edges')),stations:parse(data,'stations')},'Variable fillet'),'Fillet',true);},
 'advanced-chamfer':()=>{const b=one();modal('Two-distance chamfer',index(b)+index(b,'edges')+field('d1','Distance on reference face (mm)',2)+field('d2','Second distance (mm)',4),async data=>eng.modify(b,'chamferTwo',{faces:ids(data.get('faces')),edges:ids(data.get('edges')),distance1:val(data,'d1'),distance2:val(data,'d2')},'Asymmetric chamfer'),'Chamfer');},
 'advanced-trim':()=>{const b=one();modal('Trim supporting surface in UV',index(b)+jsonInput('loops','Outer loop, followed by hole loops (UV coordinates)',[[[0,0],[1,0],[1,1],[0,1]],[[.4,.4],[.6,.4],[.6,.6],[.4,.6]]])+note('Loops must be simple and strictly separated. UV limits are listed by Surface analysis. This creates a new trimmed face from the supporting surface; it is not a solid cut or an intersection with old face holes.'),async data=>eng.create('trimSurface',{shape:exactInput(b),faces:ids(data.get('faces')),loops:parse(data,'loops')},b.name+' · trimmed face'),'Create face',true);},
 'advanced-fit':()=>modal('Fit surface through an ordered point grid',jsonInput('points','3D point rows',Array.from({length:4},(_,i)=>Array.from({length:4},(_,j)=>[i*10,j*10,Math.sin(i)*Math.sin(j)*5])))+field('mode','Method','interpolate',{options:[['interpolate','Interpolate ordered point rows'],['approximate','Approximate to tolerance']]})+field('fitTolerance','Approximation tolerance (mm)',.01)+note('An ordered grid is required. This is not unrestricted point-cloud reconstruction.'),async data=>eng.create('fitSurface',{points:parse(data,'points'),interpolate:data.get('mode')==='interpolate',fitTolerance:val(data,'fitTolerance')},'Fitted NURBS surface'),'Fit surface',true),
 'advanced-surface':()=>{const b=one();modal('Surface differential analysis',index(b)+jsonInput('parameters','Optional UV sample locations; [] uses face center',[])+note('Reports D2 derivatives and principal/mean/Gaussian curvature on the supporting surface. Hole membership is not evaluated.'),async data=>{const parameters=parse(data,'parameters'),result=await eng.query('surfaceSample',{shape:exactInput(b),faces:ids(data.get('faces')),...(parameters.length?{parameters}:{})});setTimeout(()=>report('Surface analysis',result),0);},'Evaluate',true);},
 'advanced-heal':()=>{const b=one();modal('Heal and unify exact topology',field('repairTolerance','Maximum repair tolerance (mm)',.000001)+note('Fixes wire/orientation defects and unifies compatible same-domain faces/edges. Missing design surfaces are not invented.'),async data=>eng.modify(b,'heal',{tolerance:val(data,'repairTolerance',1e-9,.01)},'Heal exact topology'),'Heal');},
 'advanced-offset':()=>{const b=one();modal('Offset complete solid',field('distance','Signed offset (mm)',2)+note('Uses native arc joins. Local self-intersections and collapsed walls can make an offset infeasible; invalid output is rejected.'),async data=>eng.modify(b,'offsetSolid',{distance:val(data,'distance')},'Offset solid'),'Offset');},
 'advanced-split':()=>{const bs=app.ui.selectedBodies();if(bs.length<2)throw Error('Select a target body followed by one or more cutting bodies.');bs.forEach(exactInput);if(bs[0].locked)throw Error('Unlock the target.');modal('Split with tool bodies',note(`Split <b>${esc(bs[0].name)}</b> using ${bs.length-1} retained tool bodies.`),async()=>eng.run('splitByBody',{shape:exactInput(bs[0]),tools:bs.slice(1).map(exactInput)},'Split with bodies',p=>{const target=app.document.find(bs[0].id);if(!target||target.locked)throw Error('Target changed.');app.document.remove([target.id]);p.shapes.forEach((s,i)=>app.document.add(solidFromExact(s),target.name+' · '+(i+1),target.material,target.component));}),'Split');},
 'advanced-section':()=>{const b=one();modal('True section drawing',field('origin','Plane origin: x, y, z','0, 0, 0',{type:'text'})+field('normal','Plane normal: x, y, z','0, 0, 1',{type:'text'})+field('tolerance','Curve export chord tolerance (mm)',.02)+field('scale','Drawing scale',1)+field('name','Drawing name','Section A–A',{type:'text'})+jsonInput('detail','Optional detail window [x,y,width,height]; null for entire section',null),async data=>{const section=await eng.query('section',{shape:exactInput(b),origin:vector(data.get('origin')),normal:vector(data.get('normal')),tolerance:val(data,'tolerance',.001,2)});showSection(section,{name:data.get('name'),scale:val(data,'scale'),detail:parse(data,'detail')});},'Generate section',true);},
 'advanced-section-export':()=>{if(!lastSection)throw Error('Generate a section first.');modal('Export section',field('format','Format','svg',{options:[['svg','Hatched drawing SVG'],['dxf','Tolerance-sampled section DXF'],['brep','Native exact intersection BREP'],['json','Section curves and coordinates JSON']]}),data=>{const f=data.get('format');download(f==='svg'?lastSectionSVG:f==='dxf'?sectionDXF(lastSection):f==='brep'?lastSection.brep:JSON.stringify(lastSection,null,2),'Avolith-section.'+f,f==='svg'?'image/svg+xml':'text/plain');},'Export');}
};
const rows=[['advanced-fillet','Variable fillet','round','Native variable-radius fillet law'],['advanced-chamfer','Two-distance','chamfer','Native asymmetric chamfer'],['advanced-trim','UV trim','face','Real parametric trimming wires and holes'],['advanced-fit','Fit surface','loft','Interpolate or approximate an ordered 3D point grid'],['advanced-surface','Curvature','measure','D2 derivatives and curvature of supporting surfaces'],['advanced-heal','Heal B-rep','repair','Wire/orientation healing and same-domain unification'],['advanced-offset','Offset solid','shell','Whole-solid offset with native arc joins'],['advanced-split','Tool split','split','Divide solids using arbitrary native tool bodies'],['advanced-section','Section view','drawing','Hatched arbitrary-plane section and detail drawing'],['advanced-section-export','Section export','export','SVG, DXF, native BREP and JSON section export']];
const defs=Object.fromEntries(rows.map(([id,...entry])=>[id,entry])),c=id=>({id,size:'large'});
app.registerCommands(defs,{Advanced:[['Native editing',['advanced-fillet','advanced-chamfer','advanced-offset','advanced-split'].map(c)],['Surfaces',['advanced-trim','advanced-fit','advanced-surface'].map(c)],['Repair',[c('advanced-heal')]],['Drafting',['advanced-section','advanced-section-export'].map(c)]]},actions);
Object.assign(eng.actions,actions);eng.advanced={actions,get lastSection(){return lastSection;}};
