/** Advanced workbench. Native edits, numerical reports and drawing exports share undo and cancellation. */
import {exactInput,solidFromExact,exactFaceIndex} from './exact-client.js';
import {M} from '../core/math.js';
import {panelBendCSV} from './sheet-panel.js';
import {solveAssembly,applyAssemblySolution} from './assembly.js';
import {ExactClient} from './exact-client.js';
import {sectionSVG,sectionDXF} from './sections.js';
const esc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
const jsonInput=(name,label,value)=>`<label class="field engineering-json"><span>${esc(label)}</span><textarea id="f-${name}" name="${name}" rows="8" spellcheck="false">${esc(JSON.stringify(value,null,2))}</textarea></label>`;
const parse=(data,name)=>{const s=data.get(name);if(typeof s!=='string'||s.length>250000)throw Error('JSON input exceeds 250 KB.');try{return JSON.parse(s);}catch{throw Error(`Invalid JSON: ${name}.`);}};
const ids=s=>{const a=String(s).trim()?String(s).split(/[ ,;]+/).map(Number):[];if(a.some(x=>!Number.isInteger(x)||x<0))throw Error('Topology indices must be non-negative integers.');return [...new Set(a)];};
const vector=s=>{const v=String(s).split(/[ ,;]+/).map(Number);if(v.length!==3||!v.every(Number.isFinite))throw Error('Enter x, y, z coordinates.');return v;};
await new Promise(resolve=>{const poll=()=>window.avolith?.engineering?resolve():setTimeout(poll,25);poll();});
const app=window.avolith,eng=app.engineering,{field,modal,val,download,toast}=app.ui;
const note=s=>`<div class="note">${s}</div>`;
const one=()=>{const bs=app.ui.selectedBodies();if(bs.length!==1)throw Error('Select one exact body.');if(bs[0].locked)throw Error('Unlock the selected body first.');exactInput(bs[0]);return bs[0];};
const index=(b,kind='faces')=>field(kind,kind==='faces'?'Face index (zero-based)':'Edge indices; blank selects all',kind==='faces'?String(exactFaceIndex(app.state,b)??0):'',{type:'text',optional:kind==='edges'});
const report=(title,obj)=>modal(title,`<pre class="engineering-report">${esc(JSON.stringify(obj,null,2))}</pre>`,null,'Close',true);
let lastSection=null,lastSectionSVG='',lastMotion=null,motionStamp='';
const motionClient=new ExactClient(new URL('./analysis-worker.js',import.meta.url));
const originalCancel=eng.cancel;eng.cancel=()=>{originalCancel();motionClient.cancel();};
const stamp=()=>JSON.stringify({b:app.document.bodies.map(b=>[b.id,b.solid.meta.referenceKey,b.solid.meta.referenceFrame]),m:app.document.engineering.mates});
const defaultPanel={outline:[[0,0],[100,0],[100,70],[0,70]],thickness:2,kFactor:.42,grainAngle:0,flanges:[0,1,2,3].map(edge=>({edge,length:25,radius:3,angle:90,gapStart:5,gapEnd:5})),cutouts:[{kind:'circle',center:[50,35],radius:8}]};

function showSection(section,options){lastSection=section;lastSectionSVG=sectionSVG(section,options);const panel=document.getElementById('drawings');panel.innerHTML=`<div class="drawing-bar"><strong>${esc(options.name||'Section A–A')}</strong><button data-cmd="model">Back to model</button><button data-cmd="advanced-section-export">Export section</button></div><div class="engineering-sheet">${lastSectionSVG}</div>`;panel.hidden=false;app.state.drawing=true;app.state.exactDrawing=true;app.renderer.request();}
const actions={
 'panel-create':()=>{const b=app.ui.selectedBodies().length===1?app.ui.selectedBodies()[0]:null,e=b?.solid.meta.exact,edit=!!e?.sheetPanelDefinition;modal(edit?'Edit edge-flange panel':'Create edge-flange panel',jsonInput('definition','Panel outline, edge flanges, open reliefs, cutouts and grain',edit?e.sheetPanelDefinition:defaultPanel)+field('flat','Create flat development',edit?e.flat:false,{type:'checkbox',inline:true})+note('Counterclockwise base outline, zero-based edge numbers. Flange lengths exclude bend arcs. Open corner reliefs prevent overlap; measured allowance may override K-factor development. This is not stamped forming.'),async data=>{const args={definition:parse(data,'definition'),flat:data.has('flat')};if(edit){if(b.locked)throw Error('Unlock the panel.');args.pose=M.mul(e.pose,e.sheetPanelPose||M.identity());await eng.run('sheetPanel',args,'Edit panel',p=>app.document.find(b.id).solid=solidFromExact(p));app.setSelection([b.id]);}else await eng.create('sheetPanel',args,'Edge-flange enclosure');},'Build panel',true);},
 'panel-toggle':async()=>{const b=one(),e=b.solid.meta.exact;if(!e.sheetPanelDefinition)throw Error('Select an edge-flange panel. Modeling edits that remove its retained definition cannot be unfolded.');await eng.run('sheetPanel',{definition:e.sheetPanelDefinition,flat:!e.flat,pose:M.mul(e.pose,e.sheetPanelPose||M.identity())},e.flat?'Refold panel':'Unfold panel',p=>app.document.find(b.id).solid=solidFromExact(p));app.setSelection([b.id]);},
 'panel-export':()=>{const b=one(),def=b.solid.meta.exact.sheetPanelDefinition;if(!def)throw Error('Select an edge-flange panel.');modal('Export developed panel',field('format','Output','dxf',{options:[['dxf','Flat perimeter and cutouts DXF'],['svg','Flat perimeter and cutouts SVG'],['csv','Bend and grain schedule CSV'],['step','Analytic flat solid STEP']]})+note('SVG/DXF profiles are sampled from a native mid-thickness section. Bend locations and tooling inputs are in the separate CSV schedule; verify against production tooling.'),async data=>{const f=data.get('format');let result;if(f==='csv')result=panelBendCSV(def);else {const flat=await eng.query('sheetPanel',{definition:def,flat:true});if(f==='step')result=(await eng.query('exportSTEP',{shapes:[{brep:flat.brep,name:b.name+' flat'}]})).data;else{const section=await eng.query('section',{shape:flat,origin:[0,0,def.thickness/2],normal:[0,0,1],tolerance:.01});result=f==='svg'?sectionSVG(section,{name:b.name+' · developed panel'}):sectionDXF(section);}}download(result,b.name+'-flat.'+f,f==='svg'?'image/svg+xml':'text/plain');},'Export');},
 'joint-drive':()=>{const d=app.document;if(!d.engineering.mates.length)throw Error('Create assembly mates first.');modal('Drive, limit or couple a joint',field('id','Existing mate',d.engineering.mates[0].id,{options:d.engineering.mates.map(m=>[m.id,m.type+' · '+m.id])})+field('type','Joint behavior','drivenRevolute',{options:[['revolute','Free revolute with optional stops'],['slider','Free slider with optional stops'],['drivenRevolute','Driven revolute'],['drivenSlider','Driven slider'],['screw','Helical screw relationship']]})+field('value','Drive value: degrees / mm',30)+field('pitch','Screw pitch: mm per revolution',5)+jsonInput('limits','Optional stops [minimum,maximum]; null disables limits',null)+note('Angles use a single ±179° branch. Screw coupling is quasi-static and does not include thread contact. Changing the mate and solving is one undoable transaction.'),data=>{d.transact('Configure mechanical joint',()=>{const m=d.engineering.mates.find(m=>m.id===data.get('id'));if(!m)throw Error('Mate was removed.');m.type=data.get('type');m.value=val(data,'value');m.pitch=val(data,'pitch');const limits=parse(data,'limits');if(limits===null)delete m.limits;else m.limits=limits;const result=solveAssembly(d.bodies,d.engineering.mates,d.engineering.grounded);applyAssemblySolution(d,result);});toast('Joint solved.');},'Apply joint',true);},
 'joint-motion':()=>{const d=app.document,drivers=d.engineering.mates.filter(m=>['drivenRevolute','drivenSlider'].includes(m.type));if(!drivers.length)throw Error('Configure a driven revolute or slider first.');modal('Quasi-static motion study',field('id','Driver',drivers[0].id,{options:drivers.map(m=>[m.id,m.type+' · '+m.id])})+field('from','Start value',0)+field('to','End value',90)+field('frames','Number of solved frames',21,{min:2,max:121,step:1})+note('Runs in a cancellable worker on clones. No motion is applied until you choose a frame. It is not a collision or dynamics simulation.'),async data=>{const key=stamp(),r=await eng.query('motion',{bodies:d.bodies.map(b=>({id:b.id,name:b.name,locked:b.locked,solid:b.solid.toJSON()})),mates:d.engineering.mates,grounded:d.engineering.grounded,options:{mateId:data.get('id'),from:val(data,'from'),to:val(data,'to'),frames:val(data,'frames')}},motionClient);if(key!==stamp())throw Error('Assembly changed during the study.');lastMotion=r;motionStamp=key;toast('Solved '+r.frames.length+' motion frames. Use Motion results to apply/export.');},'Solve study');},
 'joint-results':()=>{if(!lastMotion)throw Error('Solve a motion study first.');modal('Motion study results',note(`${lastMotion.frames.length} solved frames · maximum residual ${Math.max(...lastMotion.frames.map(f=>f.maxResidual)).toExponential(3)} · ${esc(lastMotion.notice)}`)+field('frame','Frame index',0,{min:0,max:lastMotion.frames.length-1,step:1})+field('output','Action','export',{options:[['export','Export solved motion JSON'],['apply','Apply selected frame to assembly']]}),data=>{if(data.get('output')==='export'){download(JSON.stringify(lastMotion,null,2),'Avolith-motion.json','application/json');return;}if(stamp()!==motionStamp)throw Error('Assembly changed since this study. Recompute before applying a frame.');const i=val(data,'frame');if(!Number.isInteger(i)||!lastMotion.frames[i])throw Error('Invalid frame index.');const frame=lastMotion.frames[i];app.document.transact('Apply motion frame',()=>{applyAssemblySolution(app.document,{...frame,converged:true});app.document.engineering.mates.find(m=>m.id===lastMotion.mateId).value=frame.value;});motionStamp='';toast('Motion frame applied.');},'Continue',true);},

 'advanced-fillet':()=>{const b=one();modal('Variable-radius edge fillet',index(b,'edges')+jsonInput('stations','Normalized edge fraction and radius (mm)',[[0,1],[.5,3],[1,2]])+note('The kernel interpolates radius stations along each selected contour. Infeasible blends are rejected without changing the source.'),async data=>eng.modify(b,'filletLaw',{edges:ids(data.get('edges')),stations:parse(data,'stations')},'Variable fillet'),'Fillet',true);},
 'advanced-chamfer':()=>{const b=one();modal('Two-distance chamfer',index(b)+index(b,'edges')+field('d1','Distance on reference face (mm)',2)+field('d2','Second distance (mm)',4),async data=>eng.modify(b,'chamferTwo',{faces:ids(data.get('faces')),edges:ids(data.get('edges')),distance1:val(data,'d1'),distance2:val(data,'d2')},'Asymmetric chamfer'),'Chamfer');},
 'advanced-trim':()=>{const b=one();modal('Trim supporting surface in UV',index(b)+jsonInput('loops','Outer loop, followed by hole loops (UV coordinates)',[[[0,0],[1,0],[1,1],[0,1]],[[.4,.4],[.6,.4],[.6,.6],[.4,.6]]])+note('Loops must be simple and strictly separated. UV limits are listed by Surface analysis. This creates a new trimmed face from the supporting surface; it is not a solid cut or an intersection with old face holes.'),async data=>eng.create('trimSurface',{shape:exactInput(b),faces:ids(data.get('faces')),loops:parse(data,'loops')},b.name+' · trimmed face'),'Create face',true);},
 'advanced-fit':()=>modal('Fit surface through an ordered point grid',jsonInput('points','3D point rows',Array.from({length:4},(_,i)=>Array.from({length:4},(_,j)=>[i*10,j*10,Math.sin(i)*Math.sin(j)*5])))+field('mode','Method','interpolate',{options:[['interpolate','Interpolate ordered point rows'],['approximate','Approximate to tolerance']]})+field('fitTolerance','Approximation tolerance (mm)',.01)+note('An ordered grid is required. This is not unrestricted point-cloud reconstruction.'),async data=>eng.create('fitSurface',{points:parse(data,'points'),interpolate:data.get('mode')==='interpolate',fitTolerance:val(data,'fitTolerance')},'Fitted NURBS surface'),'Fit surface',true),
 'advanced-surface':()=>{const b=one();modal('Surface differential analysis',index(b)+jsonInput('parameters','Optional UV sample locations; [] uses face center',[])+note('Reports D2 derivatives and principal/mean/Gaussian curvature on the supporting surface. Hole membership is not evaluated.'),async data=>{const parameters=parse(data,'parameters'),result=await eng.query('surfaceSample',{shape:exactInput(b),faces:ids(data.get('faces')),...(parameters.length?{parameters}:{})});setTimeout(()=>report('Surface analysis',result),0);},'Evaluate',true);},
 'advanced-heal':()=>{const b=one();modal('Heal and unify exact topology',field('repairTolerance','Maximum repair tolerance (mm)',.000001)+note('Fixes wire/orientation defects and unifies compatible same-domain faces/edges. Missing design surfaces are not invented.'),async data=>eng.modify(b,'heal',{tolerance:val(data,'repairTolerance',1e-9,.01)},'Heal exact topology'),'Heal');},
 'advanced-offset':()=>{const b=one();modal('Offset complete solid',field('distance','Signed offset (mm)',2)+note('Uses native arc joins. Local self-intersections and collapsed walls can make an offset infeasible; invalid output is rejected.'),async data=>eng.modify(b,'offsetSolid',{distance:val(data,'distance')},'Offset solid'),'Offset');},
 'advanced-split':()=>{const bs=app.ui.selectedBodies();if(bs.length<2)throw Error('Select a target body followed by one or more cutting bodies.');bs.forEach(exactInput);if(bs[0].locked)throw Error('Unlock the target.');modal('Split with tool bodies',note(`Split <b>${esc(bs[0].name)}</b> using ${bs.length-1} retained tool bodies.`),async()=>eng.run('splitByBody',{shape:exactInput(bs[0]),tools:bs.slice(1).map(exactInput)},'Split with bodies',p=>{const target=app.document.find(bs[0].id);if(!target||target.locked)throw Error('Target changed.');app.document.remove([target.id]);p.shapes.forEach((s,i)=>app.document.add(solidFromExact(s),target.name+' · '+(i+1),target.material,target.component));}),'Split');},
 'advanced-section':()=>{const b=one();modal('True section drawing',field('origin','Plane origin: x, y, z','0, 0, 0',{type:'text'})+field('normal','Plane normal: x, y, z','0, 0, 1',{type:'text'})+field('tolerance','Curve export chord tolerance (mm)',.02)+field('scale','Drawing scale',1)+field('name','Drawing name','Section A–A',{type:'text'})+jsonInput('detail','Optional detail window [x,y,width,height]; null for entire section',null),async data=>{const section=await eng.query('section',{shape:exactInput(b),origin:vector(data.get('origin')),normal:vector(data.get('normal')),tolerance:val(data,'tolerance',.001,2)});showSection(section,{name:data.get('name'),scale:val(data,'scale'),detail:parse(data,'detail')});},'Generate section',true);},
 'advanced-section-export':()=>{if(!lastSection)throw Error('Generate a section first.');modal('Export section',field('format','Format','svg',{options:[['svg','Hatched drawing SVG'],['dxf','Tolerance-sampled section DXF'],['brep','Native exact intersection BREP'],['json','Section curves and coordinates JSON']]}),data=>{const f=data.get('format');download(f==='svg'?lastSectionSVG:f==='dxf'?sectionDXF(lastSection):f==='brep'?lastSection.brep:JSON.stringify(lastSection,null,2),'Avolith-section.'+f,f==='svg'?'image/svg+xml':'text/plain');},'Export');}
};
actions['exact-cancel']=()=>eng.cancel();
const rows=[['panel-create','Edge-flange panel','sheet','Analytic polygonal panels with multiple edge flanges'],['panel-toggle','Unfold panel','unfold','Regenerate folded or developed analytic panel'],['panel-export','Panel export','export','Native flat solid, perimeter and bend schedules'],['joint-drive','Joint drive','constraint','Driven and limited revolute/slider or screw coupling'],['joint-motion','Motion study','rotate','Worker-based quasi-static constraint continuation'],['joint-results','Motion results','chart','Apply a solved frame or export motion JSON'],['advanced-fillet','Variable fillet','round','Native variable-radius fillet law'],['advanced-chamfer','Two-distance','chamfer','Native asymmetric chamfer'],['advanced-trim','UV trim','face','Real parametric trimming wires and holes'],['advanced-fit','Fit surface','loft','Interpolate or approximate an ordered 3D point grid'],['advanced-surface','Curvature','measure','D2 derivatives and curvature of supporting surfaces'],['advanced-heal','Heal B-rep','repair','Wire/orientation healing and same-domain unification'],['advanced-offset','Offset solid','shell','Whole-solid offset with native arc joins'],['advanced-split','Tool split','split','Divide solids using arbitrary native tool bodies'],['advanced-section','Section view','drawing','Hatched arbitrary-plane section and detail drawing'],['advanced-section-export','Section export','export','SVG, DXF, native BREP and JSON section export']];
const defs=Object.fromEntries(rows.map(([id,...entry])=>[id,entry])),c=id=>({id,size:'large'});
app.registerCommands(defs,{Manufacture:[['Sheet panels',['panel-create','panel-toggle','panel-export'].map(c)],['Kinematics',['joint-drive','joint-motion','joint-results'].map(c)]],Advanced:[['Native editing',['advanced-fillet','advanced-chamfer','advanced-offset','advanced-split'].map(c)],['Surfaces',['advanced-trim','advanced-fit','advanced-surface'].map(c)],['Repair',[c('advanced-heal')]],['Drafting',['advanced-section','advanced-section-export'].map(c)]]},actions);
Object.assign(eng.actions,actions);eng.advanced={actions,get lastSection(){return lastSection;},get lastMotion(){return lastMotion;}};
